name: Production Build
on: push
jobs:
  src:
    name: build src files
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Map Branch to DEPLOYMENT
      id: check_branch
      run: |
        echo "DEPLOYMENT=$(if [[ ${GITHUB_REF##*/} = main ]]; 
            then echo "PRD"; 
        elif [[ ${GITHUB_REF##*/} = stg ]]; 
            then echo "STG"; 
        elif [[ ${GITHUB_REF##*/} = caty* ]]; 
            then echo "CATY"; 
        elif [[ ${GITHUB_REF##*/} = abu* ]]; 
            then echo "ABU"; 
        elif [[ ${GITHUB_REF##*/} = jose* ]]; 
            then echo "JOSE"; 
        elif [[ ${GITHUB_REF##*/} = steven* ]]; 
            then echo "STEVEN"; 
        elif [[ ${GITHUB_REF##*/} = * ]];
            then echo "DEV"; fi)" >> $GITHUB_ENV

    - name: Map Branch to Domain ENV VAR
      run: |
        echo "DOMAIN=$(if [[ $DEPLOYMENT = PRD ]]; 
          then echo "www.therealcapstone.com"; 
        else
          echo "${DEPLOYMENT,,}.therealcapstone.com"; fi)" >> $GITHUB_ENV

    - name: Yarn Install
      run: |
        yarn install

    - name: Production Build
      run: yarn build

    - name: Deploy to s3
      run: |
        aws s3 sync ./build s3://$DOMAIN --acl public-read --delete